apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/data-mysql-0"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-0
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume-1
  labels:
    type: local
spec:
  storageClassName: manual-1
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/data-mysql-1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-mysql-1
spec:
  storageClassName: manual-1
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
