apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: amazonaws-com
spec:
  secretName: manual-staging-tls
  issuerRef:
    name: letsencrypt-staging
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
  commonName: ec2-52-203-197-40.compute-1.amazonaws.com
  dnsNames:
  - ec2-52-203-197-40.compute-1.amazonaws.com
  - ec2-3-80-248-58.compute-1.amazonaws.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ec2-52-203-197-40.compute-1.amazonaws.com
      - ec2-3-80-248-58.compute-1.amazonaws.com