apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: peggy-com-prod
spec:
  secretName: peggy-com-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: peggy.gq
  dnsNames:
  - www.peggy.gq
  - peggy.gq
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - www.peggy.gq
      - peggy.gq