version: '3.4'

services:

  app-dev:
    image: maven:3.6-jdk-8
    working_dir: /app
    volumes:
      - ./:/app
      - ./.m2:/root/.m2 
    ports:
      - 8082:8080
    command: mvn spring-boot:run 
    restart: always

  app-prod:
    build:
      context: ./
      dockerfile: Dockerfile
    image: spring-boot-app
    ports:
      - 8083:8080
    restart: always