apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: example-com
  namespace: default
spec:
  secretName: example-com-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: ec2-3-80-248-58.compute-1.amazonaws.com
  dnsNames:
  - ec2-3-80-248-58.compute-1.amazonaws.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - ec2-3-80-248-58.compute-1.amazonaws.com
    - http01:
        ingress: my-ingress
      domains:
      - ec2-3-80-248-58.compute-1.amazonaws.com

